export const SPEC_TABLES = [
  { cat: 'prelim_general',        table: 'prelim_specs',                 name: 'Prelim General' },
  { cat: 'grid_connection',       table: 'grid_connection_app_specs',    name: 'Grid Connection' },
  { cat: 'grid_protection',       table: 'gpu_req_threshold_specs',      name: 'Grid Protection' },
  { cat: 'panels',                table: 'panel_specs',                  name: 'Panels' },
  { cat: 'inverters',             table: 'inverter_specs',               name: 'Inverters' },
  { cat: 'optimisers',            table: 'optimiser_specs',              name: 'Optimisers' },
  { cat: 'racking',               table: 'racking_specs',                name: 'Racking' },
  { cat: 'additional_racking',    table: 'additional_racking_specs',     name: 'Additional Racking' },
  { cat: 'inverter_station',      table: 'inverter_station_specs',       name: 'Inverter Station' },
  { cat: 'pvdb',                  table: 'pvdb_specs',                   name: 'PVDB' },
  { cat: 'pfc',                   table: 'pfc_specs',                    name: 'PFC' },
  { cat: 'netnada',               table: 'netnada_specs',                name: 'NetNada' },
  { cat: 'netnada_addons',        table: 'netnada_addons_specs',         name: 'NetNada Addons' },
  { cat: 'harm_filtering',        table: 'harm_filtering_specs',         name: 'Harm Filtering' },
  { cat: 'batteries',             table: 'battery_specs',                name: 'Batteries' },
  { cat: 'battery_inverter',      table: 'battery_inverter_specs',       name: 'Battery Inverter' },
  { cat: 'bessdb',                table: 'bessdb_specs',                 name: 'BESSDB' },
  { cat: 'ac_cabling',            table: 'ac_cabling_specs',             name: 'AC Cabling' },
  { cat: 'cabling_addons',        table: 'cabling_addons_specs',         name: 'Cabling Addons' },
  { cat: 'switch_gear',           table: 'switch_gear_specs',            name: 'Switch Gear' },
  { cat: 'ac_breaker',            table: 'ac_breaker_specs',             name: 'AC Breaker' },
  { cat: 'install',               table: 'install_specs',                name: 'Install' },
  { cat: 'lifting',               table: 'lifting_specs',                name: 'Lifting' },
  { cat: 'travel_accoms_freight', table: 'travel_accoms_freight_specs',  name: 'Travel Accomms Freight' },
  { cat: 'safety',                table: 'safety_specs',                 name: 'Safety' },
  { cat: 'monitoring_warranty',   table: 'monitoring_warranty_specs',    name: 'Monitoring Warranty' },
  { cat: 'monitoring_addons',     table: 'monitoring_addons_specs',      name: 'Monitoring Addons' },
];

export const UI_FIELDS: Record<string, string[]> = {
  prelim_general:        ['item_code', 'item_name', 'item_type', 'price_total'],
  grid_connection:       ['item_code', 'dnsp', 'state', 'low_size_kva', 'high_side_kva', 'app_fee_tech_assessment', 'total_network_fee', 'additional_cost', 'hv_site_variation', 'full_export_variation', 'is_bess_only', 'is_solar_or_solar_bess', 'preliminary_enquiry', 'is_project_needed', 'notes'],
  grid_protection:       ['item_code', 'dnsp', 'required_over_kva', 'is_export_limit_enforced'],
  panels:                ['item_code', 'item_name', 'brand', 'wattage', 'cost_per_watt', 'item_type', 'product_warranty', 'performance_warranty', 'is_local_stock', 'datasheet_code'],
  inverters:             ['item_code', 'brand', 'model', 'watt', 'cost_per_watt', 'warranty_years'],
  optimisers:            ['item_code', 'optimiser_name', 'size_va', 'price_per_unit'],
  racking:               ['item_code', 'racking_type', 'cost_per_panel'],
  additional_racking:    ['item_code', 'item_name', 'cost_per_item', 'unit'],
  inverter_station:      ['item_code', 'inverter_station', 'inverter_station_cost_per_unit'],
  pvdb:                  ['item_code', 'pvdb_type', 'export_limited_price', 'full_export_price'],
  pfc:                   ['item_code', 'pfc_type', 'price_per_unit'],
  netnada:               ['item_code', 'payment_plan', 'plan_type', 'price'],
  netnada_addons:        ['item_code', 'item_name', 'payment_plan', 'price'],
  harm_filtering:        ['item_code', 'item_name', 'item_type', 'price_per_unit'],
  batteries:             ['item_code', 'item_name', 'brand', 'nominal_kwh', 'battery_price_fwb', 'product_warranty', 'performance_warranty', 'is_pcs_included', 'suggested_pcs'],
  battery_inverter:      ['item_code', 'item_name', 'brand', 'kva', 'pcs_price_excl_gst'],
  bessdb:                ['item_code', 'bessdb_type', 'export_limited_price', 'full_export_price'],
  ac_cabling:            ['item_code', 'cable_type', 'size_mm2', 'conductor_material', 'price_per_type'],
  cabling_addons:        ['item_code', 'item_name', 'addon_type', 'cost_per_meter'],
  switch_gear:           ['item_code', 'item_name', 'item_type', 'total_price'],
  ac_breaker:            ['item_code', 'name', 'breaker_type', 'rating_a', 'price_per_breaker'],
  install:               ['item_code', 'install_item', 'item_type', 'price', 'unit'],
  lifting:               ['item_code', 'name', 'lifting_type', 'cost_per_time', 'number_of_lifts', 'establishments', 'is_battery_install', 'unit'],
  travel_accoms_freight: ['item_code', 'travel', 'accom', 'freight', 'distance_frm_city_center', 'travel_rates'],
  safety:                ['item_code', 'item_name', 'item_type', 'price', 'unit'],
  monitoring_warranty:   ['item_code', 'item_name', 'item_type', 'price', 'unit'],
  monitoring_addons:     ['item_code', 'item_name', 'item_type', 'price', 'unit'],
};

export const AC_MAP_FIELDS = [
  'size_mm2',
  'copper_single_core',
  'copper_4c_e',
  'alu_single_core',
  'alu_4c_e',
];
